### ISSUE TITLE
Ohh no! We couldn't start the bot.

### ISSUE THREAD

**Issue by AbilioDade** [renatofmmaia/spacecrypto-bot#11]
LOG:

[02-21 10:39] => Traceback (most recent call last):
  File "C:\Users\Abilio\.phet\Desktop\bot-new\spacecrypto-bot-main\main.py", line 28, in main
    Image.load_targets_user()
  File "C:\Users\Abilio\.phet\Desktop\bot-new\spacecrypto-bot-main\module\image.py", line 41, in load_targets_user
    Image.set_images_resolution()
  File "C:\Users\Abilio\.phet\Desktop\bot-new\spacecrypto-bot-main\module\image.py", line 197, in set_images_resolution
    im_user = np.array(Image.TARGETS_GLOBAL['screen_user'])
KeyError: 'screen_user'

**Comment by renatofmmaia** [comment]
Fala @AbilioDade, é necessario ter a imagem "**screen_user.png**" na pasta assets/images/targets_global, da uma olhada no tutorial de configuração do bot.

**Comment by AbilioDade** [comment]
Consegui o nome da meu arquivo tava com um PNG a mais. .png.png, agora ta tudo certo. 
Eu agradeço desde ja pelo bot, e gostaria de saber se vao atualizar o bot porque o space atualizou hoje e ta com uma nova opçao de mudar a pagina das naves.

**Comment by renatofmmaia** [comment]
Opa que bom, temos atualizações sim a vir, e vamos continuar dando suporte aos updates do space =)
