### ISSUE TITLE
0/15 naves

### ISSUE THREAD

**Issue by biduco07** [renatofmmaia/spacecrypto-bot#13]
ao ficar 0/15 nave o bot ele espera a wave acabar e ao abrir o popup de fail, ele clica em confirm e volta para home, após isso não faz mais nada, qual seria o próximo movimento dele ?

**Comment by biduco07** [comment]
Ops, meu confirm de victory não esta funcionando tambem.

**Comment by biduco07** [comment]
[02-21 17:05] => Traceback (most recent call last):
  File "C:\Users\Pedro Henrique\Desktop\RenatoMaia\spacecrypto-bot-main\main.py", line 68, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "C:\Users\Pedro Henrique\Desktop\RenatoMaia\spacecrypto-bot-main\module\manager.py", line 49, in do_what_needs_to_be_done
    Ship.keep_working(self)
  File "C:\Users\Pedro Henrique\Desktop\RenatoMaia\spacecrypto-bot-main\module\spaceScreen.py", line 225, in keep_working
    Ship.remove_ships()
  File "C:\Users\Pedro Henrique\Desktop\RenatoMaia\spacecrypto-bot-main\module\spaceScreen.py", line 349, in remove_ships
    x, y, w, h = Image.get_one_target_position("btn_fight_boss", screen_image=screen_img)
  File "C:\Users\Pedro Henrique\Desktop\RenatoMaia\spacecrypto-bot-main\module\image.py", line 159, in get_one_target_position
    raise Exception(f"{target} not found")
Exception: btn_fight_boss not found

Log do erro.

**Comment by hiagopinacio** [comment]
Sua resolução é 1360 x 768?
verifica se sua print ficou com as bordas certinhas.

diminui os threshold no arquivo de config (nao pode diminuir muito). tenta:

```
threshold:
  default: 0.7
  to_work: 0.8
```

testei aqui em 1366x768  e funcionou

**Comment by biduco07** [comment]
Resolvido, coloquei na resolução 1366 x 768, fiz o print certinho com as bordas e importantíssimo tirei o favoritos.
Meu threshold: 
  default: 0.65
  to_work: 0.85
  
(default a 0.7 não estava reconhecendo a tela home).
Fechando Issues e obrigado pela ajuda.
