### ISSUE TITLE
Erro no bot

### ISSUE THREAD

**Issue by pikapows** [renatofmmaia/spacecrypto-bot#14]
Ele só coloca 3 naves depois da erro, retira as 3 e coloca de novo e fica assim pra sempre.

[02-21 18:40] => Traceback (most recent call last):
  File "C:\spg\main.py", line 68, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "C:\spg\module\manager.py", line 49, in do_what_needs_to_be_done
    Ship.keep_working(self)
  File "C:\spg\module\spaceScreen.py", line 297, in keep_working
    while not Ship.check_number_of_ships(Image.screen(), n_ships):
  File "C:\spg\module\spaceScreen.py", line 327, in check_number_of_ships
    x, y, w, h = Image.get_one_target_position("identify_n_space_shipts_in_battle_start_area", screen_image=screen_img)
  File "C:\spg\module\image.py", line 159, in get_one_target_position
    raise Exception(f"{target} not found")
Exception: identify_n_space_shipts_in_battle_start_area not found

**Comment by hiagopinacio** [comment]
Opa, boa noite. 
Tente diminuir os threshold no arquivo config.
Aproveite e atualiza o bot, pois lançamos uma versão com algumas correções.
