### ISSUE TITLE
Nao Funciona na Resolução 1366x768

### ISSUE THREAD

**Issue by frleandro** [renatofmmaia/spacecrypto-bot#22]
[02-22 07:36] => Traceback (most recent call last):
  File "C:\spg\main.py", line 68, in main
    manager.do_what_needs_to_be_done(current_screen)
  File "C:\spg\module\manager.py", line 49, in do_what_needs_to_be_done
    Ship.keep_working(self)
  File "C:\spg\module\spaceScreen.py", line 230, in keep_working
    Ship.remove_ships()
  File "C:\spg\module\spaceScreen.py", line 362, in remove_ships
    x, y, w, h = Image.get_one_target_position("btn_fight_boss", screen_image=screen_img)
  File "C:\spg\module\image.py", line 159, in get_one_target_position
    raise Exception(f"{target} not found")
Exception: btn_fight_boss not found

**Comment by niknachtigal** [comment]
Conseguiu fazer funcionar na resolução 1366x768? Alterou o que?
