### ISSUE TITLE
😬 Ohh no! We couldn't start the bot.

### ISSUE THREAD

**Issue by kr4toos19** [renatofmmaia/spacecrypto-bot#7]
😬 Ohh no! We couldn't start the bot.

**Comment by renatofmmaia** [comment]
Qual o erro esta acusando no arquivo de log? ele fica em log/logger.txt, cola ele aqui para que eu possa te ajudar

**Comment by biduco07** [comment]
[02-20 22:01] => Traceback (most recent call last):
  File "C:\Users\Pedro Henrique\Desktop\spacecrypto-bot-main (4)\spacecrypto-bot-main\main.py", line 28, in main
    Image.load_targets_user()
  File "C:\Users\Pedro Henrique\Desktop\spacecrypto-bot-main (4)\spacecrypto-bot-main\module\image.py", line 41, in load_targets_user
    Image.set_images_resolution()
  File "C:\Users\Pedro Henrique\Desktop\spacecrypto-bot-main (4)\spacecrypto-bot-main\module\image.py", line 197, in set_images_resolution
    im_user = np.array(Image.TARGETS_GLOBAL['screen_user'])
KeyError: 'screen_user'

(o log de erro de: 😬 Ohh no! We couldn't start the bot.)

**Comment by AbilioDade** [comment]
O meu deu a mesma coisa.

**Comment by renatofmmaia** [comment]
Pessoal, é necessário ter a imagem "screen_user.png" na pasta assets/images/targets_global, da uma olhada no tutorial de configuração do bot.
